apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
        selector: mssql
    spec:
      terminationGracePeriodSeconds: 30 
      hostname: mssqlinst 
      securityContext: 
        fsGroup: 10001 
      containers:
      - name: my-mssql
        image: myregistry.domain.com:5001/mssql-server:2017
        #image: myregistry.domain.com:5001/my-ubuntu:latest
        #image: mcr.microsoft.com/mssql/server:2019-latest
        command: ['/tmp/run.sh']
        #imagePullPolicy: Always
        ports:
          - containerPort: 1433
        env:
          - name: SA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mssql-secret
                key: sa_password
          - name: ACCEPT_EULA
            value: {{ .Values.accept_eula | quote }}
          - name: MSSQL_PID
            value: {{ .Values.mssql_pid | quote }}
        volumeMounts:
        - name: mssql-data
          mountPath: /var/opt/mssql
        - name: start-script
          mountPath: /tmp
        # resources:
        #   limits:
        #     memory: "3Gi"
        #     cpu: "500m"

      volumes:
      - name: mssql-data
        persistentVolumeClaim:
          claimName: db-pvc
      - name: start-script
        configMap:
          name: start-script
          defaultMode: 0744
